name: Format suggestions
on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled, unlabeled ]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls -la
          cat .JuliaFormatter.toml
      - uses: julia-actions/julia-format@v4
        with:
          version: '1'
          suggestion-label: 'format-suggest'